### PR TITLE
switch to serde_json

### PR DESCRIPTION
**Pull request by silvio**
Signed-off-by: Silvio Fricke silvio.fricke@gmail.com

### CODE REVIEW

**Comment by tailhook** [comment]
Would you mind providing some reasoning? Will rustc_serialize be deprecated? Why serde_json is superior? Why shouldn't we support both?

**Comment by silvio** [comment]
A support of both libraries would be great and should the way to go. rustc_serialize is "marked for death". Please read [this](https://www.reddit.com/r/rust/comments/3v4ktz/differences_between_serde_and_rustc_serialize/)

**Comment by tailhook** [comment]
> A support of both libraries would be great

Looks easy. Would you mind updating the pull request?

**Comment by silvio** [comment]
I'm new to rust. Would be greate to give me a hint for this.

My first approach was a `enum JsonValue` with two entries in `src/json_struct.rs`. One for rustc_serialize and other one for serde.
With this approach I run in a borrow checker problem. But I doesn't get it fixed. I'm sure - its easy ^^

Have a look at https://github.com/silvio/rust-gron/commit/54cb16b41a1d57f439902b1104b4fac9a518c10e

**Comment by tailhook** [comment]
Well, to fix that problem you need to play around with let binding, like this:

```
let variable = Value::from_str(..).unwrap();
...
&variable
```

But this isn't going to be accepted, sorry :)

You must not clone object and convert it by serializing it to a string. It's too expensive for such a simple thing.

What I expect you to do:
1. Simplest solution: just two different functions, one accepting serde and one rust_serialize. They are totally separate.
2. We can use it under umbrella of a single function. For that to work you need to declare a separate trait. Add another generic type to the `json_to_gron` function. And implement that trait for two kinds of values (just use two functions made as part of bullet point 1 above)

Does it makes sense for you?

**Comment by silvio** [comment]
Make sense for me.

I will try your suggestions. Thanks.

**Pull request closed without merging**
